(define (make-rational num den)
	(cons num den))
(define (numerator rat)
	(car rat))
(define (denominator rat)
	(cdr rat))
(define (*rat a b)
	(make-rational (* (numerator a) (numerator b))
				   (* (denominator a) (denominator b))))
(define (+rat a b)
	(make-rational (+ (numerator a) (numerator b))
				   (+ (denominator a) (denominator b))))
(define (print-rat rat)
	(word (numerator rat) '/ (denominator rat)))
	
(define call1 (print-rat (make-rational 2 3)))
(define call2 (print-rat (*rat (make-rational 2 3) (make-rational 1 4))))
(define call3 (print-rat (+rat (make-rational 2 3) (make-rational 1 4))))